open Funct4;;

let resFA1 = GenFA1.gen ~fracfree:false;;
let resFA2 = GenFA2.gen ~fracfree:false;;
let resFA3 = GenFA3.gen ~fracfree:false;;
let resFA4 = GenFA4.gen ~fracfree:true;;
let resFV1 = GenFV1.gen ~fracfree:false;;
let resFV2 = GenFV2.gen ~fracfree:false;;
let resFV3 = GenFV3.gen ~fracfree:false;;
let resFV4 = GenFV4.gen ~fracfree:true;;
let resIA1 = GenIA1.gen ~fracfree:false;;
let resIA2 = GenIA2.gen ~fracfree:false;;
let resIA3 = GenIA3.gen ~fracfree:false;;
let resIA4 = GenIA4.gen ~fracfree:true;;
let resIV1 = GenIV1.gen ~fracfree:false;;
let resIV2 = GenIV2.gen ~fracfree:false;;
let resIV3 = GenIV3.gen ~fracfree:false;;
let resIV4 = GenIV4.gen ~fracfree:true;;

let rFA1 = .! resFA1 ;;
let rFA2 = .! resFA2 ;;
let rFA3 = .! resFA3 ;;
let rFA4 = .! resFA4 ;;
let rFV1 = .! resFV1 ;;
let rFV2 = .! resFV2 ;;
let rFV3 = .! resFV3 ;;
let rFV4 = .! resFV4 ;;
let rIA1 = .! resIA1 ;;
let rIA2 = .! resIA2 ;;
let rIA3 = .! resIA3 ;;
let rIA4 = .! resIA4 ;;
let rIV1 = .! resIV1 ;;
let rIV2 = .! resIV2 ;;
let rIV3 = .! resIV3 ;;
let rIV4 = .! resIV4 ;;
